
// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app"
// };

export default function Layout({ params: { event_id }, children }) {
    // TODO: get current event
    // TODO: get current user
    // TODO: show header

    return (
        <>
            {children}
        </>
    );
}