import Provider from "./provider";
import { Inter } from "next/font/google";

const inter = Inter({
    subsets: ["latin", "cyrillic-ext"],
    display: "swap",
    variable: "--font-inter"
});

import "@radix-ui/themes/styles.css";
import "@/styles/common.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function Layout({ children }) {
    return (
        <html lang="en" className={inter.variable}>
            <body>
                <Provider>
                    {children}
                </Provider>
            </body>
        </html>
    );
}