create table public.events (
    id bigint generated by default as identity,
    name text not null,
    image text null,
    chief_judge text null,
    chief_secretary text null,
    start_date date not null default now(),
    is_active boolean not null default false,

    constraint events_pkey primary key (id)
) tablespace pg_default;