create table public.judges (
    id bigint generated by default as identity,
    user_id uuid not null,
    nomination_id bigint not null,
    
    constraint judges_pkey primary key (id),
    constraint judges_nomination_id_fkey foreign key (nomination_id) 
        references nominations (id) 
        on update cascade 
        on delete cascade,
    constraint judges_user_id_fkey foreign key (user_id) 
        references auth.users (id)
) tablespace pg_default;