create table public.performances (
    id bigint generated by default as identity,
    start_time time without time zone null,
    nomination_id bigint not null,
    age_id bigint not null,
    team text null,
    members text null,
    coach text null,
    is_editable boolean not null default false,
    is_active boolean not null default false,
    
    constraint performances_pkey primary key (id),
    constraint performances_nomination_id_fkey foreign key (nomination_id) 
        references nominations (id) on update cascade on delete cascade
    constraint public_performances_age_id_fkey foreign key (age_id) 
        references ages (id) on update cascade on delete cascade
) tablespace pg_default;