create table public.profiles (
    id bigint generated by default as identity,
    user_id uuid not null,
    given_name text not null,
    role public.role not null,
    
    constraint users_pkey primary key (id),
    constraint users_user_id_key unique (user_id),
    constraint profiles_user_id_fkey foreign key (user_id) 
        references auth.users (id) 
        on update cascade 
        on delete cascade
) tablespace pg_default;